### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by YokohamaAIart** [npjonath/covid19QRGeneratorBot#1]
Hi,

I encounter the below error message when running the script.
Can you help please?

Many thanks.

[issue.txt](https://github.com/npjonath/covid19QRGeneratorBot/files/6837594/issue.txt)

**Comment by MikeLowrey2k** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/covid19QRGeneratorBot/covid_bot.py", line 91, in <module>
    bot = CovidFrenchCertificateBot()
  File "/home/kali/covid19QRGeneratorBot/covid_bot.py", line 29, in __init__
    self.driver = webdriver.Chrome()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by MikeLowrey2k** [comment]
didnt work this bitch
